---
development:
  cloud_name: dajydvrqu
  api_key: "551533498585976"
  api_secret: nxEv84jXa-Ebiw1qZJA0-q_fpqw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dajydvrqu
  api_key: "551533498585976"
  api_secret: nxEv84jXa-Ebiw1qZJA0-q_fpqw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dajydvrqu
  api_key: "551533498585976"
  api_secret: nxEv84jXa-Ebiw1qZJA0-q_fpqw
  enhance_image_tag: true
  static_image_support: false
